# Generated by Django 5.1.4 on 2026-03-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField(db_index=True)),
                ('id_driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('id_rider', models.ForeignKey(db_column='id_rider', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ride',
                'verbose_name_plural': 'rides',
                'db_table': 'rides',
                'ordering': ['-pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('id_ride', models.ForeignKey(db_column='id_ride', on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='rides.ride')),
            ],
            options={
                'verbose_name': 'ride event',
                'verbose_name_plural': 'ride events',
                'db_table': 'ride_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='idx_ride_status'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='idx_ride_pickup_coords'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['id_ride', 'created_at'], name='idx_ride_event_ride_created'),
        ),
    ]
